[components]
model = "epifx.det.SEEIIR"
time = "pypfilt.Datetime"
summary = "pypfilt.summary.HDF5"

[parameters]
particles = 1000
prng_seed = 3001
data_dir = "."
out_dir = "."
max_days = 7
resample.threshold = 0.25
resample.regularisation = true
fresh_cache = true
remove_cache = true
time.start = "2014-01-01"
time.until = "2014-10-31"
summary.from_first_day = true
summary.only_forecasts = true
summary.metadata.packages = [ "epifx" ]

[model.priors]
R0 = { function = "uniform", args.low = 1.35, args.high = 1.45 }
sigma = { function = "inverse_uniform", args.inv_low = 0.2, args.inv_high = 0.3 }
gamma = { function = "inverse_uniform", args.inv_low = 0.2, args.inv_high = 0.3 }
eta = { function = "uniform", args.low = 1.0, args.high = 1.0 }
alpha = { function = "uniform", args.low = 0.0, args.high = 0.0 }
t0 = { function = "uniform", args.low = 0.0, args.high = 28.0 }

[model.bounds]
R0 = { min = 1.35, max = 1.45 }
sigma = { min = 0.2, max = 0.3 }
gamma = { min = 0.2, max = 0.3 }
eta = { min = 1.0, max = 1.0 }
alpha = { min = 0, max = 0 }
t0 = { min = 0, max = 28 }

[summary.monitors]
exp_obs_monitor.model = "pypfilt.summary.ExpectedObsMonitor"
peak_monitor.model = "epifx.summary.PeakMonitor"
peak_monitor.init.exp_obs_monitor = "exp_obs_monitor"
thresh_500.model = "epifx.summary.ThresholdMonitor"
thresh_500.init.threshold = 500
thresh_1000.model = "epifx.summary.ThresholdMonitor"
thresh_1000.init.threshold = 1000

[summary.tables]
model_cints.model = "pypfilt.summary.ModelCIs"
param_covar.model = "pypfilt.summary.ParamCovar"
forecasts.model = "pypfilt.summary.PredictiveCIs"
forecasts.init.exp_obs_monitor = "exp_obs_monitor"
forecasts.init.probs = [0, 50, 95]
pr_epi.model = "epifx.summary.PrOutbreak"
obs_llhd.model = "epifx.summary.ObsLikelihood"
peak_size_acc.model = "epifx.summary.PeakSizeAccuracy"
peak_size_acc.init.peak_monitor = "peak_monitor"
peak_time_acc.model = "epifx.summary.PeakTimeAccuracy"
peak_time_acc.init.peak_monitor = "peak_monitor"
peak_cints.model = "epifx.summary.PeakForecastCIs"
peak_cints.init.peak_monitor = "peak_monitor"
peak_ensemble.model = "epifx.summary.PeakForecastEnsembles"
peak_ensemble.init.peak_monitor = "peak_monitor"
"obs/cases".model = "epifx.summary.Obs"
"obs/cases".init.obs_units = "cases"
exceed_500.model = "epifx.summary.ExceedThreshold"
exceed_500.init.thresh_monitor = "thresh_500"
exceed_500.init.start = "2014-04-01"
exceed_500.init.until = "2014-10-01"
exceed_500.init.width = 7
exceed_1000.model = "epifx.summary.ExceedThreshold"
exceed_1000.init.thresh_monitor = "thresh_1000"
exceed_1000.init.start = "2014-04-01"
exceed_1000.init.until = "2014-10-01"
exceed_1000.init.width = 7
expected_obs.model = "epifx.summary.ExpectedObs"
expected_obs.init.exp_obs_monitor = "exp_obs_monitor"
expected_obs.init.probs = [0, 50, 95]

[scenario.test]
name = "seeiir_test"
parameters.model.population_size = 1_000_000
sample_lookup_tables = [ "pr_obs" ]

[scenario.test.lookup_tables]
pr_obs = "pr-obs.ssv"

[scenario.test.observations.cases]
model = "epifx.obs.PopnCounts"
init.obs_period = 7
init.pr_obs_lookup = "pr_obs"
file = "weekly-cases.ssv"
file_args.time_col = "date"
file_args.value_col = "cases"
parameters.bg_obs = 200
parameters.bg_var = 3000
parameters.pr_obs = 0.5
parameters.disp = 100
format = { bg_obs = "03.0f", bg_var = "03.0f", pr_obs = "0.1f", disp = "03.0f" }
name = { bg_obs = "bg", bg_var = "bgvar", pr_obs = "pr", disp = "disp" }
