version: 2

build:
  image: latest

python:
  version: 3.6
  install:
    - requirements: requirements.txt
    - requirements: requirements-rtd.txt
    - method: setuptools
      path: .

sphinx:
  configuration: doc/conf.py
